[package]
name = "flights-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4" }
actix-web-prom = "0.6.0"
env_logger = "0.9.0"
futures = "0.3"
log = "0.4.0"
prometheus = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
